In [0]:
#First I tried with numpy only
from numpy import exp, array, random, dot

In [0]:

from numpy import exp, array, random, dot
import numpy as np

class ANN:
  def __init__(self):
    self.synaptic_weights_1 = np.array([[0.2,-0.3],[0.4,0.1],[-0.5,0.2]])
    self.synaptic_bias_1    = np.array([0.4,0.2])
    self.synaptic_weights_2 = np.array([[-0.3,0.2,0.6],[-0.2,-0.1,-0.2,]])
    self.synaptic_bias_2    = np.array([0.1,0.1,0.2])
    self.synaptic_weights_3 = np.array([[0.3,0.2],[-0.5,0.5],[0.7,0.2]])
    self.synaptic_bias_3    = np.array([-0.1,-0.2])
    self.lr=0.9
    
  
  def print_weights(self):
    print("weights...")
    print(self.synaptic_weights_1,self.synaptic_weights_1.shape)
    print(self.synaptic_weights_2,self.synaptic_weights_2.shape)
    print(self.synaptic_weights_3,self.synaptic_weights_3.shape)
    
  def __sigmoid(self, x):
    return 1 / (1 + exp(-x))

  def __sigmoid_derivative(self, x):
    return x * (1 - x)
  
  def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
    for iteration in range(number_of_training_iterations):
        o1 = self.think(training_set_inputs,self.synaptic_weights_1,self.synaptic_bias_1)
        o2 = self.think(o1,self.synaptic_weights_2,self.synaptic_bias_2)
        o3 = self.think(o2,self.synaptic_weights_3,self.synaptic_bias_3)
        
        print("outputs\n",o1,o2,o3)
        
        e3 = dot(dot(o3,1-o3),training_set_outputs-o3)
        e2 = dot(dot(o2,1-o2),np.dot(e3,self.synaptic_weights_3.reshape(2,3)))
        e1 = dot(dot(o1,1-o1),np.dot(e2,self.synaptic_weights_3.reshape(3,2)))
        
        print("error\n",e1,e2,e3)
        
        del_weight_3 = self.lr*e3*o3
        del_weight_2 = self.lr*e2*o2
        del_weight_1 = self.lr*e1*o1
        
        print("del_weights\n",del_weight_1,del_weight_2,del_weight_3)        
        
        self.synaptic_weights_1 = self.synaptic_weights_1 + del_weight_1
        self.synaptic_weights_2 = self.synaptic_weights_2 + del_weight_2
        self.synaptic_weights_3 = self.synaptic_weights_3 + del_weight_3
        
        self.print_weights()

  def think(self, inputs,weights,bias):
    return self.__sigmoid(dot(inputs, weights)+bias)

  

In [8]:
inp=np.array([1,0,1])
out=np.array([1,0])


ann=ANN()
ann.print_weights()
ann.train(inp,out,1)

weights...
[[ 0.2 -0.3]
 [ 0.4  0.1]
 [-0.5  0.2]] (3, 2)
[[-0.3  0.2  0.6]
 [-0.2 -0.1 -0.2]] (2, 3)
[[ 0.3  0.2]
 [-0.5  0.5]
 [ 0.7  0.2]] (3, 2)
outputs
 [0.52497919 0.52497919] [0.45946675 0.53805077 0.60108588] [0.54725226 0.56982469]
error
 [-0.02332579 -0.04564644] [-0.05413518 -0.11195652 -0.12358003] [ 0.22315562 -0.28086188]
del_weights
 [-0.011021   -0.02156709] [-0.02238598 -0.05421446 -0.06685399] [ 0.10991018 -0.14403783]
weights...
[[ 0.188979   -0.32156709]
 [ 0.388979    0.07843291]
 [-0.511021    0.17843291]] (3, 2)
[[-0.32238598  0.14578554  0.53314601]
 [-0.22238598 -0.15421446 -0.26685399]] (2, 3)
[[ 0.40991018  0.05596217]
 [-0.39008982  0.35596217]
 [ 0.80991018  0.05596217]] (3, 2)


In [1]:
#And then I tried with Keras
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

Using TensorFlow backend.


In [0]:
hidden_weight_1=np.array([[0.2,-0.3],[0.4,0.1],[-0.5,0.2]])
hidden_bias_1=np.array([0.4,0.2])
hidden_weight_2=np.array([[-0.3,0.2,0.6],[-0.2,-0.1,-0.2]])
hidden_bias_2=np.array([0.1,0.1,0.2])
hidden_weight_3=np.array([[0.3,0.2],[-0.5,0.5],[0.7,0.2]])
hidden_bias_3=np.array([-0.1,-0.2])
weights=[hidden_weight_1,hidden_bias_1,hidden_weight_2,hidden_bias_2,hidden_weight_3,hidden_bias_3]

In [3]:
model = Sequential()
h1 = model.add(Dense(2,activation="sigmoid",input_dim=3))
h2=model.add(Dense(3,activation="sigmoid"))
o = model.add(Dense(2,activation="sigmoid"))
model.compile(loss="mean_squared_error",optimizer="Adam",metrics=['accuracy'])
model.set_weights(weights)


W0902 16:48:36.471134 140354220689280 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0902 16:48:36.520877 140354220689280 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0902 16:48:36.529679 140354220689280 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0902 16:48:36.577399 140354220689280 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:793: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0902 16:48:36.628501 140354220689280 deprecation_wrappe

In [4]:
x=np.array([[1,0,1]])
y=np.array([[1,0]])
model.fit(x,y,epochs=1)

Epoch 1/1
1/1 [==============================] - 0s 385ms/step - loss: 0.2648 - acc: 0.0000e+00


In [5]:
model.get_weights()

[array([[ 0.20072854, -0.2992777 ],
        [ 0.4       ,  0.1       ],
        [-0.49927148,  0.20072232]], dtype=float32),
 array([0.40072852, 0.20072232], dtype=float32),
 array([[-0.299259  ,  0.19925602,  0.6007438 ],
        [-0.19925901, -0.10074399, -0.19925624]], dtype=float32),
 array([0.10074248, 0.09925594, 0.20074394], dtype=float32),
 array([[ 0.3007441,  0.1992559],
        [-0.4992559,  0.4992559],
        [ 0.7007441,  0.1992559]], dtype=float32),
 array([-0.09925589, -0.20074412], dtype=float32)]